const modules = await Promise.all([
  import("../src/ids.mjs"),
  import("../src/model.mjs"),
  import("../src/schema.mjs"),
  import("../src/store.mjs"),
  import("../src/local-database.mjs"),
  import("../src/indexeddb-driver.mjs"),
  import("../src/file-intake.mjs"),
  import("../src/indexeddb-file-content-store.mjs"),
  import("../src/ink-format.mjs"),
  import("../src/today-query.mjs"),
  import("../src/lecture-flow.mjs"),
  import("../src/lecture-inbox.mjs"),
  import("../src/library-search.mjs"),
  import("../src/offline-queue.mjs"),
  import("../src/backup.mjs"),
  import("../src/academic-repository.mjs"),
]);

const requiredExports = [
  ["createStableId", "isStableId", "assertStableId"],
  [
    "createAcademicYear",
    "createSemester",
    "createCapabilityPack",
    "createSubjectProfile",
    "createSubject",
    "createScheduleEntry",
    "createLecture",
    "createTask",
    "reviseTask",
    "LECTURE_STATUSES",
    "TASK_STATUSES",
    "TASK_PRIORITIES",
    "createFileArtifact",
    "createFileHash",
    "createFileVersion",
    "createArtifactLink",
    "FILE_SOURCE_TYPES",
    "ARTIFACT_LINK_TARGET_KINDS",
    "ARTIFACT_LINK_ROLES",
    "createNotebook",
    "createInkDocument",
    "createInkRevision",
    "NOTEBOOK_TEMPLATES",
    "INK_FORMAT_VERSION",
    "createResourceMarker",
    "reviseResourceMarker",
    "RESOURCE_TARGET_KINDS",
    "createNote",
    "reviseNote",
  ],
  ["CORE_SCHEMA_VERSION", "createEmptySnapshot", "migrateSnapshot", "validateSnapshot"],
  ["CoreStore", "CoreRelationError"],
  ["CoreLocalDatabase", "CorePersistenceError", "CoreRecoveryError"],
  ["IndexedDbCoreDriver", "INDEXED_DB_VERSION"],
  ["sha256Hex", "prepareFileIntake", "assertFileContentStore"],
  ["IndexedDbFileContentStore", "FILE_CONTENT_DB_VERSION", "FILE_CONTENT_STORE"],
  ["prepareInkSnapshot", "parseInkSnapshot"],
  ["buildTodayQuery"],
  [
    "createLectureCapture",
    "createLectureCloseout",
    "completeLectureCloseout",
    "createCaptureResolution",
    "LECTURE_CAPTURE_KINDS",
    "LECTURE_CLOSEOUT_STATUSES",
    "CAPTURE_RESOLUTION_OUTCOMES",
  ],
  ["buildLectureInbox"],
  [
    "buildLibraryIndex",
    "searchLibrary",
    "listFavoriteResources",
    "listRecentResources",
  ],
  [
    "createOfflineOperation",
    "startOfflineOperation",
    "succeedOfflineOperation",
    "failOfflineOperation",
    "conflictOfflineOperation",
    "retryOfflineOperation",
    "recoverInterruptedOperation",
    "OFFLINE_OPERATION_STATUSES",
  ],
  [
    "PORTABLE_BACKUP_FORMAT",
    "PORTABLE_BACKUP_VERSION",
    "BackupValidationError",
    "BackupRestoreConflictError",
    "createPortableBackup",
    "verifyPortableBackup",
    "restorePortableBackup",
  ],
  [
    "AcademicRepository",
    "AcademicRepositoryRecoveryRequiredError",
    "LectureCloseoutIncompleteError",
  ],
];

for (let index = 0; index < modules.length; index += 1) {
  for (const name of requiredExports[index]) {
    if (!(name in modules[index])) throw new Error(`Missing core export: ${name}`);
  }
}

console.log("Studio5 core module contract check passed");
